; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower
board_build.filesystem_size = 0.5m

; Dépendances de librairies
lib_deps =
    https://github.com/TheHappyGrey/PicoGFX_SSD1322.git
    adafruit/Adafruit GFX Library
    adafruit/Adafruit BusIO
    adafruit/Adafruit TinyUSB Library @ ^3.1.4
    fortyseveneffects/MIDI Library @ ^5.0.2

    mathertel/RotaryEncoder @ ^1.5.3
    adafruit/Adafruit PCF8574 @ ^1.1.0
    bblanchon/ArduinoJson @ ^7.0.4

; Options de compilation
build_flags =
    -DUSE_TINYUSB
    -DCFG_TUD_MIDI=1
    -DPIO_FRAMEWORK_ARDUINO_ENABLE_RTTI

lib_ignore = 
    SdFat - Adafruit Fork

; Moniteur série
monitor_speed = 115200
monitor_filters = 
    send_on_enter
    colorize
